steps:
# Step 1: Set up environment - Install required tools
- name: 'gcr.io/cloud-builders/curl'
  id: 'install-dependencies'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y jq curl
      jq --version # Verify jq is installed

# Step 2: Debugging - Print Substitution Values
- name: 'gcr.io/cloud-builders/gcloud'  # You can use any image with echo
  id: 'debug-substitutions'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      echo "Debugging Substitution Values:"
      echo "PROJECT_ID: $PROJECT_ID"
      echo "_LOCATION: ${_LOCATION}"
      echo "_CORPUS_NAME: ${_CORPUS_NAME}"
      echo "_CORPUS_DISPLAY_NAME: ${_CORPUS_DISPLAY_NAME}"

# Step 3: Create a RAG Corpus
- name: 'gcr.io/cloud-builders/curl'
  id: 'create-rag-corpus'
  entrypoint: 'bash'
  args:
    - '-c'
    - |
      apt-get update && apt-get install -y jq curl
      jq --version 

      PROJECT_ID=${PROJECT_ID}
      LOCATION="${_LOCATION}"
      CORPUS_NAME=${_CORPUS_NAME}
      DISPLAY_NAME=${_CORPUS_DISPLAY_NAME}
      
      echo "{
            \"displayName\": \"rag corpus macro data",
            \"name\": \"my-corpus-rag\"
        }" > corpus_payload.json

      cat ./corpus_payload.json 

      # Create the RAG corpus
      curl -X POST \
        -H "Authorization: Bearer $(gcloud auth print-access-token)" \
        -H "Content-Type: application/json" \
        -v \
        "https://$${LOCATION}-aiplatform.googleapis.com/v1/projects/${PROJECT_ID}/locations/$${LOCATION}/ragCorpora" \
        -d @corpus_payload.json
      


# Substitution variables
substitutions:
  _LOCATION: 'us-central1'         # API location (e.g., us-central1)
  _CORPUS_NAME: 'my-rag-corpus'    # Corpus name
  _CORPUS_DISPLAY_NAME: 'My RAG Corpus'  # Human-readable corpus name
 

timeout: '1800s'  # 30-minute timeout

options:
  logging: CLOUD_LOGGING_ONLY